package com.gamovation.core.ui.theme

import androidx.compose.ui.graphics.Color

val boardBorderColor = Color(0xFF8f542c)
val boardBackgroundColor = Color(0xFF1e2622)
val md_theme_dark_primary = Color(0xFFB3C5FF)
val md_theme_dark_onPrimary = Color(0xFF002B75)
val md_theme_dark_primaryContainer = Color(0xFF003FA4)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE1FF)
val md_theme_dark_secondary = Color(0xFF23DDD4)
val md_theme_dark_onSecondary = Color(0xFF003734)
val md_theme_dark_secondaryContainer = Color(0xFF00504C)
val md_theme_dark_onSecondaryContainer = Color(0xFF54FAF0)
val md_theme_dark_tertiary = Color(0xFFFFB1C2)
val md_theme_dark_onTertiary = Color(0xFF5F112C)
val md_theme_dark_tertiaryContainer = Color(0xFF7C2942)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002116)
val md_theme_dark_onBackground = Color(0xFF84F8CC)
val md_theme_dark_surface = Color(0xFF002116)
val md_theme_dark_onSurface = Color(0xFF84F8CC)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F909A)
val md_theme_dark_inverseOnSurface = Color(0xFF002116)
val md_theme_dark_inverseSurface = Color(0xFF84F8CC)
val md_theme_dark_inversePrimary = Color(0xFF0055D5)
val md_theme_dark_surfaceTint = Color(0xFFB3C5FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)

